### PR TITLE
Bump dependencies to Play 2.4.6 compatibility

### PR DESCRIPTION
**Pull request by pedrorijo91**
Solves #18

### CODE REVIEW

**Comment by poweld** [comment]
Looks good, thank you for your contribution :+1:

**Comment by pedrorijo91** [comment]
Are you planning to make a release soon?

**Comment by poweld** [comment]
I've bumped the version up to `1.0` and cut a release which should propagate out to mvn shortly.

**Comment by pedrorijo91** [comment]
thanks a lot ! btw, it may be useful to other users to make this lib use sem version (http://semver.org/), but that's up to you :)

**Pull request merged**
